name: Prod Pipeline
on:
  pull_request:
    branches:
      - main
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Tests
        run: pytest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t galgu/polybot:$GITHUB_SHA .

      - name: Push Docker Image
        run: docker push galgu/polybot:$GITHUB_SHA

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to AWS EC2 and Run `kubectl` Commands
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /path/to/k8s/
            kubectl apply -f deployment.yaml
            kubectl apply -f service.yaml
          EOF
